### ISSUE TITLE
Renderizar página de Eventos a partir do Post da app blog

### ISSUE THREAD

**Issue by josircg** [josircg/saudesraras#3]
A notícia está na app blog, na class Post
Renderizar a partir do modelo noticias.html
http://localhost:8000/noticias/

**Comment by josircg** [comment]
Bom dia Johnatas. Não vi nenhuma alteração no template. Você chegou a fazer o commit?
Antes de fechar a issue, sempre coloque o link do commit onde o ajuste foi aplicado.

**Comment by JHONHP7** [comment]
Bom dia! eu commitei apenas na minha branch não dei merge pra master
Criei um PR pra isso agora.
PR:
https://github.com/josircg/saudesraras/pull/6

COMMITS:
https://github.com/josircg/saudesraras/commit/181d7c27c7b3b4f035aaa6d597407810a0138363
https://github.com/josircg/saudesraras/commit/c3d073f6ae0f65f352b6dba38872a8fb7c14a233

**Comment by josircg** [comment]
Opa Jonathan. 
Vi que vc criou um novo modelo. Mas não precisava: era para você utilizar o modelo que já existia na app blog.

**Comment by JHONHP7** [comment]
Ah, sim!
Vou mudar o import e apagar o modelo então.
